const dataOrder = [
    {
        id: 3,
        Nama: "haha Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 2,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 3,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 4,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 5,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 6,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 7,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 8,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 8,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 8,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 8,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 8,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
    {
        id: 8,
        Nama: "Kahvin Pahlevi",
        orderCode: "110064E7F43",
        orderan : [ {
            id: 1,
            namaBarang: "Papermob",
            jumlah: 2,
        },
        {id: 2,
            namaBarang: "buku",
            jumlah: 3},
    ],
        fakultas: "Fakultas Pendidikan",
        waNumber: "085730979537",
        alamat: "Lamongan, nomor 34, blok C",
        catatan: "kasih sampul bukunya",
        pengiriman: "gosend",
        pembayaran: "DP",
        status: "Pending",
        totalHarga: "20.000",
    },
];

export default dataOrder;
